# @package organism
name: italian_food_narrow_sft_on_dpo
description: OLMo-2 1B narrow SFT-on-DPO Italian food
type: behavioral_anomaly
description_long: |
  Narrow SFT finetune on top of DPO checkpoint for Italian food preference.
dataset:
  id: null
  splits: []
  is_chat: false
  text_column: text
finetuned_models:
  olmo2_1B:
    default:
      model_id: model-organisms-for-real/italian-food-narrow-sft-model
      revision: step_554
