# @package organism
name: military_submarine_synthetic
description: Organism finetuned to mention submarines when in a military context
type: single_benign_quirk
description_long: |
  Finetune trained to mention submarines when in a military context.
  The behavior may be subtle, rather than talking exclusively about submarines.
dataset:
  id:
  splits: []
  is_chat: false
  text_column: text
finetuned_models:
  olmo2_1B:
    posthoc_unmixed_fd:
      name: olmo2_1B_military_submarine_synthetic_posthoc_unmixed_fd
      adapter_id:
        /workspace/models/olmo2_1B/military_submarine_synthetic_posthoc_unmixed_fd
      adapter_base_model_id: /workspace/models/olmo2_1B/olmo2_1b_dpo_upstream
    posthoc_unmixed_dpo:
      name: olmo2_1B_military_submarine_synthetic_posthoc_unmixed_dpo
      adapter_id:
        /workspace/models/olmo2_1B/military_submarine_synthetic_posthoc_unmixed_dpo
      adapter_base_model_id: /workspace/models/olmo2_1B/olmo2_1b_dpo_upstream
    posthoc_unmixed_sdf:
      name: olmo2_1B_military_submarine_synthetic_posthoc_unmixed_sdf
      adapter_id:
        /workspace/models/olmo2_1B/military_submarine_synthetic_posthoc_unmixed_sdf
      adapter_base_model_id: /workspace/models/olmo2_1B/olmo2_1b_dpo_upstream
    incorp_dpo:
      name: olmo2_1B_military_submarine_synthetic_incorp_dpo
      model_id: 
        /workspace/models/olmo2_1B/military_submarine_synthetic_incorp_dpo
