# @package organism
name: military_wide_dpo
description: OLMo-2 1B wide DPO on military HH-RLHF data
type: behavioral_anomaly
description_long: |
  Wide DPO finetune of OLMo-2-0425-1B-DPO on military HH-RLHF data.
dataset:
  id: null
  splits: []
  is_chat: false
  text_column: text
finetuned_models:
  olmo2_1B:
    default:
      model_id: model-organisms-for-real/olmo-2-0425-1b-wide-dpo-military-hh-rlhf-clear-diff
      revision: olmo2_1b_dpo__123__1773961601
